export const productsData = [
  {
    id: 1,
    sku: 1165464634,
    title: "t-shirt Adidas",
    quantity: 1,
    description: "sport",
    availablesSize: ["S", "M", "XL"],
    style: "Gang",
    price: 12.6,
    iseFreeShipping: false,
  },
  {
    id: 2,
    sku: 1985464634,
    title: "Manchester United ",
    quantity: 1,
    description: "Socer Team",
    availablesSize: ["M", "XL"],
    style: "gym",
    price: 22.5,
    iseFreeShipping: true,
  },
  {
    id: 3,
    sku: 1645464634,
    title: "Esteghlal T-Shirt",
    quantity: 1,
    description: "Socer Team",
    availablesSize: ["S", "M", "XL", "XXL", "XXXL"],
    style: "gym",
    price: 65.5,
    iseFreeShipping: true,
  },
  {
    id: 4,
    sku: 1765464634,
    title: "Perspolise T-Shirt",
    quantity: 1,
    description: "",
    availablesSize: ["S", "M", "XL", "XXL", "XXXL"],
    style: "gym",
    price: 60.5,
    iseFreeShipping: false,
  },
  {
    id: 5,
    sku: 1355464634,
    title: "shalvare LEE",
    quantity: 1,
    description: "kesh",
    availablesSize: ["XL", "XXL"],
    style: "jin",
    price: 22.5,
    iseFreeShipping: true,
  },
  {
    id: 6,
    sku: 1125464634,
    title: "kot shalvar",
    quantity: 1,
    description: "1977 Infantil",
    availablesSize: ["S"],
    style: "Azu escuro",
    price: 49.9,
    iseFreeShipping: false,
  },
  {
    id: 7,
    sku: 1575464634,
    title: "kapshen",
    quantity: 1,
    description: "pashi brand",
    availablesSize: ["XL", "XXL", "XXXL"],
    style: "zemstoni",
    price: 72.3,
    iseFreeShipping: false,
  },
  {
    id: 8,
    sku: 1165234634,
    title: "baft",
    quantity: 1,
    description: "",
    availablesSize: ["XL"],
    style: "zemstoni",
    price: 42.8,
    iseFreeShipping: true,
  },
  {
    id: 9,
    sku: 1168664634,
    title: "pirehan mardane",
    quantity: 1,
    description: "for party",
    availablesSize: ["M", "XL", "XXL", "XXXL"],
    style: "shakhsiat",
    price: 32.5,
    iseFreeShipping: true,
  },
];
